### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/tempCycleways#6]
Opening this issue as a place to discuss next steps on this. Discussion below, plan to keep this first message as a place to track agreed plans for next steps. Estimates of time taken for different tasks in roughly descending order of importance below.

## Phase 1

- [ ] Implement method for automating the refinement of results based on crowd-sourced feedback and update methods accordingly (2 day)
- [ ] National roll-out of method to cover all local authorities in England based on CyIPT data (2 days)
- [ ] Deploy results in interactive web map (2 days)
- [ ] Elicit and incorporate feedback from the community via sites such as basecamp (2 days)
- [ ] Refine results to include additional variables such as existing infrastructure and road width (2 days)

## Phase 2

- [ ] Adapt the methodology to highlight roads that serve key destination (5 days)
- [ ] Adding additional trip types to key destinations: schools (5 days)
- [ ] Develop new cycling potential estimates to key destinations such as hospitals  and supermarkets, adaptable to changes in government priorities (15)
- [ ] Refine results for different types of settlements (e.g. urban vs rural, high vs low density areas) based on feedback from local authorities (5 days)
- [ ] Adapt the evidence in line with changes to government policy as it evolves (5 days)
- [ ] Generate evidence on pavement width to support social distancing for pedestrians (10 days)
- [ ] Update the results in an interactive web map (5 days)

Heads-up @mem48, @joeytalbot and @mvl22
